name: 🔁 Update Daily Quote

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get complete history for proper merging

      - name: Fetch latest changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull origin main

      - name: Fetch quote from API
        id: get-quote
        run: |
          response=$(curl -s https://zenquotes.io/api/today)
          echo "$response" > quote.json
          QUOTE=$(jq -r '.[0].q + " — " + .[0].a' quote.json)
          echo "QUOTE=${QUOTE}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "/<!-- QUOTE_START -->/,/<!-- QUOTE_END -->/c\<!-- QUOTE_START -->\n> ${QUOTE}\n<!-- QUOTE_END -->" README.md

      - name: Commit and push changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔁 Update daily quote: $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push origin main
          fi